name: Repo dispatch on prs
on:
  repository_dispatch:
    types: [run-e2e-from-safe-react-on-pr]
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      uses: actions/setup-node@v2
    - run: npm install
    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm test load_safe TESTING_ENV=PR PR=${{ github.event.client_payload.pr_number }}